// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Ov4kLIJAayGw3qFlT50RlQks0iuOlCY',
    appId: '1:662007818234:web:c3d2c191ef5adff3902643',
    messagingSenderId: '662007818234',
    projectId: 'eservices-f953c',
    authDomain: 'eservices-f953c.firebaseapp.com',
    storageBucket: 'eservices-f953c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOCD4CylQW-N4jFtr3TRZ6WKeK1cTtcyo',
    appId: '1:662007818234:android:cad3b1011391b1f3902643',
    messagingSenderId: '662007818234',
    projectId: 'eservices-f953c',
    storageBucket: 'eservices-f953c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_JnQI3D0ly1saQEbUGxB498IUW-zB7ZQ',
    appId: '1:662007818234:ios:405e5eb0e9e5f8de902643',
    messagingSenderId: '662007818234',
    projectId: 'eservices-f953c',
    storageBucket: 'eservices-f953c.appspot.com',
    iosBundleId: 'com.example.eServices',
  );
}
